import type { AuthorNote } from '../models/author-note'

interface AuthorNotesFileEntry {
  note: string
  updatedAt?: number | null
}

interface AuthorNotesFile {
  [chapterId: string]: AuthorNotesFileEntry
}

/**
 * Author's notes are short freeform text a novel author attaches to a
 * published chapter (the "A note from <author>" box on the reading
 * page). They deliberately live outside `library.sqlite`.
 *
 * The published database is treated as read-only, generated output
 * (see docs/web-novel-reader-architecture.md #6 — "The reader never
 * modifies the author's published database"), regenerated by the
 * import pipeline. Notes are the opposite: small, frequent, per-
 * chapter edits an author wants to make without regenerating the
 * whole database. So they ship as their own static JSON file, at the
 * same conventional location as `library.sqlite` and cover assets:
 * `public/content/author-notes.json`. `scripts/set-chapter-note.py`
 * is the supported way to write it.
 *
 * Missing file, missing chapter entry, empty text, and network
 * failure are all treated identically — no note — so an author who
 * hasn't written one yet just gets an empty state on the reading
 * page, never a broken box or a console error.
 */
export class AuthorNotesRepository {
  private cache: AuthorNotesFile | null = null
  private loadPromise: Promise<AuthorNotesFile> | null = null

  constructor(private readonly url = '/content/author-notes.json') {}

  async getNote(chapterId: string): Promise<AuthorNote | null> {
    const file = await this.ensureLoaded()
    const entry = file[chapterId]

    if (!entry || !entry.note || !entry.note.trim()) {
      return null
    }

    return {
      chapterId,
      note: entry.note,
      updatedAt: entry.updatedAt ?? null,
    }
  }

  private async ensureLoaded(): Promise<AuthorNotesFile> {
    if (this.cache) {
      return this.cache
    }

    if (!this.loadPromise) {
      this.loadPromise = this.fetchFile()
    }

    this.cache = await this.loadPromise

    return this.cache
  }

  private async fetchFile(): Promise<AuthorNotesFile> {
    try {
      const response = await fetch(this.url)

      if (!response.ok) {
        return {}
      }

      const data = (await response.json()) as unknown

      return data && typeof data === 'object'
        ? (data as AuthorNotesFile)
        : {}
    } catch {
      return {}
    }
  }
}
